### PR TITLE
japanese translation

### PR DESCRIPTION
**Pull request by uehaj**
This is Japanese translation of elm tutorial.
This translated into Japanese. I am happy to accept this pull requests.

### CODE REVIEW

**Comment by sporto** [comment]
This is great thanks. Please note that I am updating the tutorial to Elm 0.18. Any chance that you could revise this PR with the 0.18 updates in a few days? I would let you know when done.

**Comment by uehaj** [comment]
Thanks for your reaction, of course. It is also desirable. I will update this PR according to version 0.18.

**Comment by sporto** [comment]
Ok, I will let you know in a few days when the update is done. Thanks.

**Comment by sporto** [comment]
Hi, I finished updating the tutorial to 0.18. Can you have a look and update the PR? Thanks

**Comment by uehaj** [comment]
It is Japanese version corresponding to Elm 0.18 version. If you do not mind please merge.

**Comment by sporto** [comment]
Done, thanks

**Comment by uehaj** [comment]
Thanks!

**Pull request merged**
