### PR TITLE
Html.App to Html.program

### PR DESCRIPTION
**Pull request by jebab**
Hi i was doing the tutorial, and i found that the code was not running, guess that it's just missing an update as i saw that the english version is correct !

### CODE REVIEW

**Comment by sporto** [comment]
Hi, thanks, someone needs to do a more comprehensive update of the French version.

**Comment by Augustin82** [comment]
Someone sure does =P
I'll try to get back to it ASAP.

**Comment by jebab** [comment]
thanks for your hard work, i went throught the english tutorial, and i found it great. 
I'm not really busy at work these days, do you need some help, for the french version ?small warning : i m a beginner in elm!
--
Envoi sécurisé avec Tutanota. Obtenez votre adresse email chiffrée aujourd'hui!
https://tutanota.com

14. Déc 2016 17:54 de notifications@github.com:

**Comment by Augustin82** [comment]
Oh, the actual hard work is from @vjousse =)
You're more than welcome to help, regardless of your level; I'm a beginner in Elm too.
Feel free to join us in the #france channel on the community Slack (elmlang.slack.com, is it?) for questions and support.
Looking forward to your contributions, thanks for your interest!

**Comment by vjousse** [comment]
Be sure to visit us on the #france slack channel!

I'm updating the french version here: https://github.com/sporto/elm-tutorial/tree/french-0.18

**Pull request closed without merging**
