### PR TITLE
French translation : chapter 1

### PR DESCRIPTION
**Pull request by vjousse**
This is a work in progress: translating the full tutorial into french.

### CODE REVIEW

**Comment by sporto** [comment]
Do you want to translate the whole thing and merge? Or start merging little bit?

**Comment by vjousse** [comment]
Maybe one PR per chapter? We could merge after each chapter so that it stays coherent. I'll let you know when the foundations chapter is done.

**Comment by vjousse** [comment]
Chapter 1 is ok for me. I can't really try it with gitbook (can I?), but as far as I can tell, everything should be ok to be merged.

**Comment by sporto** [comment]
Great, I'm merging, if something looks wrong just send me another PR.

**Comment by sporto** [comment]
In the readme it would be great if you add some credits for the translation with your name on those. Could you send me another PR with this?

**Pull request merged**
